### ISSUE TITLE
Is "Please replace # with GH- in the commit message next time" needed?

### ISSUE THREAD

**Issue by cjw296** [python/bedevere#149]
This one keeps catching me out, if bedevere can spot the pattern to generate the warning, could it not just pick out what it needs?

eg: https://github.com/python/cpython/pull/11176

**Comment by Mariatta** [comment]
This explains why it can only be caught after you merged.
https://github.com/python/bedevere/issues/14#issuecomment-361452851

The automerge by miss-islington takes care of the commit message, so I suggest using the automerge label.

**Comment by cjw296** [comment]
Sorry, I couldn't really follow that discussion, it's mixed in with a whole bunch of other stuff.

Speaking of miss-islington, often seeing double-processing from her, eg: https://github.com/python/cpython/pull/11266

I have to admit, I'm not fan of squash commits anyway, but just going with the flow and trying to get stuff done...

**Comment by Mariatta** [comment]
> Sorry, I couldn't really follow that discussion, it's mixed in with a whole bunch of other stuff.

The actual answer is in here: https://github.com/python/bedevere/issues/14#issuecomment-361461960, but I'll give you time to read through the discussion.
Short answer is that you'll need to change the commit message. It cannot be changed after you merged, and therefore the only thing we can do is to remind you to change it in future commits.

> Speaking of miss-islington, often seeing double-processing from her, eg: python/cpython#11266

The double message is known issue (https://github.com/python/miss-islington/issues/109), and there is no easy fix for it.

> How long do I need to leave automerge on before it takes effect?

The automerge will happen after:
 - CLA has been signed (there is `CLA signed` label in the PR), and
- All status checks completed and green, and
- Approved by a core dev (there is `awaiting merge` label in the PR)

Hope this helps.

I'm closing this issue since there is no bug to be fixed.
