### ISSUE TITLE
Improve state graph

### ISSUE THREAD

**Issue by brettcannon** [python/bedevere#184]
https://github.com/python/bedevere/pull/182 made it a bit obvious that some edge descriptions are a bit too simple to properly convey what's going on, e.g. the "New PR" edge labels don't distinguish that in one case it's for PRs from core devs and the other is for everyone else. It would probably be  good to touch up the graph to make it more self-evident how things are supposed to work.

**Comment by lysnikolaou** [comment]
It might be a good idea to include an additional edge color for triager actions. Won't make too big of a difference right now, but it could come in handy in the future.

**Comment by ssd71** [comment]
I would like to work on this

**Comment by lysnikolaou** [comment]
Hey @ssd71, you can go ahead and push a PR for this, when you are ready.

**Comment by DanielNoord** [comment]
@brettcannon I'm not sure if the devguide was around when this issue was created but this information is now also stored on:
https://devguide.python.org/triage/labels/index.html

However, there isn't a flow graph there. Do we want to duplicate the information in this repository? Or do we want to move the graph over to the dev guide?

**Comment by brettcannon** [comment]
@DanielNoord I don't think the devguide page existed when I opened this issue.

As for where a graph should go, it's an interesting question. If you view it as user documentation then the devguide is the best spot. But if you view it as documentation to help maintain the code, then here is best. And there's also the concern of the devguide's version becoming outdated (although I don't think the overall flow has changed much since it's initial design).

So unfortunately I don't have a good answer.

**Comment by brettcannon** [comment]
> that's obviously something for you to decide!

It's actually for @Mariatta to decide as I have stepped down from maintaining Bedevere. 😁

**Comment by hugovk** [comment]
If it is worth keeping, we could put it in Markdown in this repo and have it automatically rendered, using Mermaid:

https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by ezio-melotti** [comment]
> @brettcannon I'm not sure if the devguide was around when this issue was created but this information is now also stored on:
https://devguide.python.org/triage/labels/index.html

Note that this is not up-to-date and updating it is on my todo list.  (see also https://github.com/orgs/python/projects/25/views/1)

> https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

Cool! I didn't know about this.

**Comment by ezio-melotti** [comment]
> As for where a graph should go, it's an interesting question.

My plan is to:
* add the graph to the README here (see #500)
* document the labels and link to the graph in the devguide (https://github.com/python/devguide/pull/930)

I think readers of the devguide are more interested in the meaning of the currently applied label, rather than the full flow chart -- if they are curious they can always follow the link.

> And there's also the concern of the devguide's version becoming outdated

 I'll add a couple of comments to make sure that changes are reflected in both places.
