### ISSUE TITLE
Avoiding labeling draft PRs with "awaiting review"

### ISSUE THREAD

**Issue by isidentical** [python/bedevere#210]
Bedevere doesn't check if the PR is a draft or not, it automatically labels with `awaiting review` or `awaiting core review`. The downside of this is when you search labeled PRs you still encounter with draft PRs which states they are draft so you should pass them until it becomes a normal PR. If agreed I can submit a patch for adding a check if a PR is draft or not.

**Comment by brettcannon** [comment]
Honestly people shouldn't be submitting draft PRs in the first place. We prefer people do draft PRs in there own fork and then send the PR to CPython when it's ready for review. And now that we have GitHub Actions support everyone gets CI in their fork so there's no need to do a draft PR just to see what CI says.

So honestly I would rather have a discussion at https://discuss.python.org/c/core-workflow/8 about whether we should automatically close draft PRs.

**Comment by isidentical** [comment]
> And now that we have GitHub Actions support everyone gets CI in their fork so there's no need to do a draft PR just to see what CI says.

Right, but there are workflows that are specific to pull requests like test with buildbots labels (instead of pushing upstream's buildbot branch) might be a cool way to use draft PRs to ensure if everything works on every platform and collect stats?

**Comment by terryjreedy** [comment]
"everyone gets CI in their fork" To do this, would I make a PR to merge my fork branch into my fork master?  (But never actually merge?)  And then what?  Perhaps something should be added to the devguide.

**Comment by brettcannon** [comment]
@terryjreedy if you look at https://github.com/python/cpython/blob/master/.github/workflows/build.yml you will notice it says any push/merge to master, 3.8, and 3.7 will trigger a run and then any PR that targets those branches. We could loosen those restrictions so that they run on push to any branch so people don't have to do the PR step on their own forks.

And something could be added to the devguide, but I think we should simplify the `on` trigger rules first as I think they are overly restrictive.
