### ISSUE TITLE
bedevere/issue-number status check message is cut off

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#46]
We're only seeing: ```No issue number prepended to the title or "skip is...``` 
https://github.com/python/cpython/pull/2975

<img width="727" alt="screen shot 2017-08-14 at 7 26 30 pm" src="https://user-images.githubusercontent.com/5844587/29299883-a57abd82-8126-11e7-845d-37ee59bab1c9.png">

**Comment by brettcannon** [comment]
Yep, GitHub will visibly truncate any description with an ellipsis if it goes past what the web page will allow for. If you hover over the text it will show you the entire string.

It's also controlled by CSS so there's no hard rule as to what it will truncate at (e.g. they don't say in the their dev docs, "if you keep it to 50 characters it will typically fit" or something). IOW the situation sucks and I already worried about this. 😁 

I guess we could do `No issue number in title or "skip issue" label found`, but that's 52 characters and doesn't point out that the issue number should be at the beginning (I would rely on the Details link but I've gotten enough grief from people that those links aren't discoverable enough to rely on that).

`No issue # in title or "skip issue" label found`? 47 characters, so that's short enough.

**Comment by zware** [comment]
I'm not sure that the `or "skip issue" label found` part is worth the extra characters since only core team members can set labels anyway.

**Comment by brettcannon** [comment]
I left that off initially and contributors were saying things like "does this really need a news entry?", so having it there so they know there's an option to not open an issue has a purpose. (Messaging is hard. 😉 )

**Comment by zware** [comment]
Ok, fair enough :)
