### ISSUE TITLE
Automate adding linked-pull-request symbol under "Milestones" column of the issue tracker

### ISSUE THREAD

**Issue by OTheDev** [python/bedevere#539]
When scanning the issue tracker, I find it is helpful to know whether a PR has already been linked. For example, the last entry in the image below:

![Screen Shot 2566-02-17 at 15 49 00](https://user-images.githubusercontent.com/116417456/219597800-047f8d36-dd0d-43ed-b782-2e681c3aaa3d.png)

The "linked pull request" symbol (inventing a name here (: as I don't know what to call it) appears, when, for example, the issue number is explicitly written by the PR author in the PR body (e.g. `#issue-number` -- typically the author writes something like ``Closes #issue-number``).

I think it would be nice if this could be automated by bedvedere :). I'm not familiar with the `bedvedere` code, but just based on a quick scan through the repo, it looks like a quick fix would be to ensure ``#issue-number`` gets expanded somewhere in:

https://github.com/python/bedevere/blob/8fa99c83abf0614ee1a247b4f340b9f132cd38cc/bedevere/util.py#L14-L23

Any thoughts?

**Comment by ezio-melotti** [comment]
If a PR is linked to an issue, it means (afaiu) that merging the PR will also close the issue.  This is not compatible with our workflow, because most issues also need additional PRs for backports before they can be closed.

#501 suggested a different solution and has a discussion about the limitations of the "linked pull requests" feature.
