### ISSUE TITLE
Bedevere shouldn't add "awaiting review" label on draft PRs

### ISSUE THREAD

**Issue by itamaro** [python/bedevere#554]
I noticed that when opening draft PRs on the cpython repo, Bedevere still goes ahead and adds the "awaiting review" label.
I don't want to spam with review requests for PRs that are not ready for review (hence "draft"), so I'd like to suggest modifying the state machine to acknowledge the draft state (e.g. don't add any labels until the PR is published).

**Comment by itamaro** [comment]
I'm happy to try to make this change myself (maybe with some guidance as I never touched this codebase before :) )

**Comment by Mariatta** [comment]
I think the main change is on here:

https://github.com/python/bedevere/blob/main/bedevere/stage.py#L104
Here, we're handling the "pull_request.opened" webhook event, and apply either the `awaiting review` or `awaiting core review` label.

Since the webhook event sends the `draft` status as True or False, we can use that to determine whether or not we should apply the label when the PR is opened.

```
if event.data["draft"] is False:
# apply label
```

We should also add apply the label when the PR was changed from `draft` to `ready to review`. So we may need to add the decorator `@router.register("pull_request", action="edited")`.

**Comment by Mariatta** [comment]
And I guess we should also handle the situation when the PR was changed from "ready to review" back to the "draft" state.
