### ISSUE TITLE
Add docs label for PRs that touch Doc/tools/.nitignore

### ISSUE THREAD

**Issue by skirpichev** [python/bedevere#616]
See e.g. https://github.com/python/cpython/pull/114280 or https://github.com/python/cpython/pull/114194

**Comment by hugovk** [comment]
Good idea!

I found it a bit annoying the label is added for PRs touching rst files in `Docs/`, but not those touching rst plus `.nitignore`.

**Comment by skirpichev** [comment]
PR: #617

**Comment by ezio-melotti** [comment]
> I found it a bit annoying the label is added for PRs touching rst files in Docs/, but not those touching rst plus .nitignore.

Why does this happen?  Isn't bedevere already adding the `docs` label whenever at least an `.rst` file has been changed, regardless of the other files?

**Comment by skirpichev** [comment]
Looking in the sources, it doesn't add any labels (pr_labels == []) if there is some file, which doesn't match known patterns:
https://github.com/python/bedevere/blob/b5bcd24e79ad72b47582f89f7e7053f5b3157fa4/bedevere/prtype.py#L42-L51
Another case: #605

**Comment by ezio-melotti** [comment]
So the problem is the `return` (prematurely?) terminating the loop?  Is that intentional?

**Comment by skirpichev** [comment]
> Is that intentional?

I guess - so.  Or every pr that has some ``*.rst`` file could skip news.

**Comment by AlexWaygood** [comment]
> > Is that intentional?
> 
> I guess - so. Or every pr that has some `*.rst` file could skip news.

That wouldn't be correct — there are lots of PRs that introduce new features and add docs for the new feature as part of the same PR. Most of those PRs need news entries.

**Comment by skirpichev** [comment]
(On another hand, most PRs, that touch only test files - probably could skip news;)  That's another story, however.)

**Comment by ezio-melotti** [comment]
Ok, so the goal is to add the `docs` label only to PRs that are "docs-only", i.e. they only change documentation and possibly files related to the documentation (like `.nitignore`).  If a PR adds a new feature and edits the docs to document it, it's not "docs-only" and shouldn't get the `docs` label.

(Maybe this should be spelled out clearly in a comment/docstring, including the expected behavior for other labels, since the intention is currently not too clear IMHO).
